### ISSUE TITLE
Creating PlotMe World

### ISSUE THREAD

**Issue by DeJay6424** [WorldCretornica/PlotMe-Core#60] opened 2014-12-29 23:29 UTC
Spigot-1.7.10-(1.8.0)-Snapshot
Minecraft Version: 1.7.10
When I run the command:
/mv create plotworld normal -g PlotMe-DefaultGenerator
It DOES create a plotworld. But doing any of the plotme commands internal error my server.
When I run the command /plotme auto I get this error:
http://pastebin.com/eFykZRkf

**Comment by MattBDev** [comment] 2015-01-01 00:57
@DeJay6424 is this fixed in 0.15.2 ? Please let me know so I can close this issue

**Comment by MattBDev** [comment] 2015-01-03 16:12
No reply so best assumption is that the issue is closed.

**Closed by MattBDev** 2015-01-03 16:12 UTC
Labels: bug, help wanted
