### ISSUE TITLE
Plot border breakable

### ISSUE THREAD

**Issue by SecretlyJealous** [WorldCretornica/PlotMe-Core#292] opened 2015-06-02 12:57 UTC
Users are able to place a sticky pistion on a plot and use a lever to pull back a slab and because it's in their plot area they are allowed to break the slab. This doesn't work for corners and it's not possible to push the slab back, only pulling the slab is possible.
![image](https://cloud.githubusercontent.com/assets/10485646/7936166/f3be375c-092e-11e5-8d11-5a5eea746559.png)

**Comment by jomo** [comment] 2015-06-02 12:59
Duplicate of #250?

**Comment by SecretlyJealous** [comment] 2015-06-02 13:12
Oh sorry, didn't realise that someone already made an issue about this.

**Comment by MattBDev** [comment] 2015-06-02 15:43
I fixed this 2 months ago.

**Closed by MattBDev** 2015-06-02 15:43 UTC
