### ISSUE TITLE
Plot doesn't exist.

### ISSUE THREAD

**Issue by GotScrub** [WorldCretornica/PlotMe-Core#101] opened 2015-01-16 17:28 UTC
Whoever helps me out, thank you for trying.

So I use MultiVerse along with PlotMe on my Prison server I've been working on recently. The plotme works absolutely perfect other than the fact that other non-opped people can't /plot h username and tp to someone else's plot. It tells them the plot doesn't exist.
At first, I thought it was a problem with Multiverse so we even tried it while they were in the plotme world. I want to say that it's a problem with my naming or generation of the plotme world. Could anyone help me out with the exact command to make a plotme world that allows all these commands?

**Comment by GotScrub** [comment] 2015-01-16 20:19
Bump?

**Comment by MarkusAV** [comment] 2015-01-16 21:42
Sorry for late answer.
Are you saying that players can't tp to other players plots? If so, they need to have the required permission nodes that can be found at http://worldcretornica.github.io/PlotMe-Core/cp.html
If you allready have given the permission nodes but it still doesn't work, check if your plotworld name is in all lowercase in the configurations

**Comment by GotScrub** [comment] 2015-01-17 05:37
Yeah, I'm saying they can't tp other player's plots, it says something along the lines of 'that plot doesn't exist'. They do have all the perm nodes given to them and the plotworld name is lowercase in the config.

**Comment by MarkusAV** [comment] 2015-01-17 22:27
Have you modified the captions file? There is no message in PlotMe that says "that plot doesn't exist", or "that plot" at all. Do you have any other plugins that could have done this? You'd also have to type the full username of the player that you are going to, eg. you need to do /plot home Notch not /plot home Not

**Comment by GotScrub** [comment] 2015-01-17 22:42
Yeah, updated problem. I tested it out myself this time rather than my player's POV. I tried it while not being opped and with normal default group permissions. Now when I do /p h username or /plotme h username or /plotme home username, etc. Of any username, it teleports me back to my plot.

And I think what they meant by the plot doesn't exist is the message that says "Username" doesn't have a plot" although they were tabbing the correct name.

**Comment by GotScrub** [comment] 2015-01-17 22:54
I can also send you a list of all the plugins I have and you could skim over it and see if there's any obvious interferences if you have the time?

**Comment by MarkusAV** [comment] 2015-01-17 22:56
Won't need that - Have you checked if the player you are trying to tp to have a plot at all?

**Comment by MattBDev** [comment] 2015-01-17 23:02
Here is the command format for going to another players plot:
/plotme home:1 <world> <playername> or /plotme home:1 <playername>

**Comment by GotScrub** [comment] 2015-01-18 01:06
I did /plotme home:1 playername and /plotme home:1 [world] playername. Neither worked, it's just bringing me to the plotworld spawn now, not even my own plot anymore.. And yes, the player I'm trying to go to does have a plot.

**Comment by MarkusAV** [comment] 2015-01-18 09:49
Would you mind giving me the IP to your server so I could test this myself?
Are you also running the latest Spigot and PlotMe version?

**Comment by GotScrub** [comment] 2015-01-18 18:30
I'm using 1.7.10 Bukkit and the corresponding version of PlotMe. At least I believe I am. 

My server IP though is: 142.4.218.166:25598

You should be able to do /plotme auto upon joining and all. And then you can test out trying to go to the plots: Orthdntst_ GotScrub

If you need to see plugins, just do /? and what not, you probably already know that. If you need to see any of my configs, please ask.

If you have issues on the server upon joining, just reply with what I need to fix and I'll get right on it right when I get your message.

**Comment by MattBDev** [comment] 2015-01-18 19:32
The issue is a typo in version 0.13f. This is an issues forum for 0.15+. This has been fixed in the newer versions if you choose to update.

**Closed by MattBDev** 2015-01-18 19:32 UTC
Labels: help wanted, invalid

**Comment by GotScrub** [comment] 2015-01-18 20:07
Okay, well may I use this same issue thread in order to talk about my new issue? I took your advice and upgraded to .15. I downloaded the newest .zip folder and I wasn't quite sure how to install these so I dragged the whole .zip into my plugins folder after deleting my older version of plotme. (.13f). That didn't work so I tried dragging in all the .jars in the .zip into my plugins folder and that hasn't worked. It gives me: "An internal error occurred while attempting to perform this command" when trying to display the help page or do any commands within PlotMe.

**Comment by MattBDev** [comment] 2015-01-18 20:11
There are instructions on the resource page that you need to follow in order to upgrade to the new version of plotme.

**Comment by MattBDev** [comment] 2015-01-18 20:11
PS You don't need PlotmeDynmap unless you have Dynmap installed.

**Comment by GotScrub** [comment] 2015-01-18 20:44
Following it now. Why isn't the Bukkit plugin finder updated to .15? You guys don't like Bukkit anymore or? I know you moved your page to Spigot, but.

**Comment by GotScrub** [comment] 2015-01-18 21:02
Okay, I followed the PlotMe | Upgrading steps to try and upgrade. I believe I did upgrade considering the commands are all working fine and everything. Yet, I'm now back to the original problem. It teleports me to my own /p h when I do /plotme home username or /plotme home:1 username or /plotme home:1 world username or /p h username or /plot h username or /plotme h username. I've tried on multiple accounts and I've changed the generator and everything. 

If nothing else, should I just erase my current plotworld, generate a new one since there's a new generator or something, and see if that works? There's people with plots on here, so they'd lose their things. But we'll be able to save most of it so it's not a huge deal.

**Comment by MarkusAV** [comment] 2015-01-19 15:04
Are you still at 1.7.10?

**Comment by GotScrub** [comment] 2015-01-19 16:14
So is there no way for me to use PlotMe without 1.8? :( I'd love to upgrade but a ton of people still use 1.7.10 and all my plugins are for 1.7.10 since that's what I was building for.

**Comment by EvilOlaf** [comment] 2015-01-19 16:15
There is. Get 0.13f from dev.bukkit.org

**Comment by MattBDev** [comment] 2015-01-19 16:15
There are ways to update without 1.8 but I highly recommend using 1.8

**Comment by GotScrub** [comment] 2015-01-19 19:27
EvilOlaf, I tried that but they said that the problem I was having, discussed in this issue, was a bug inside of .13f so I updated to .15 but now .15 isn't compatible with 1.7.10...

**Comment by MattBDev** [comment] 2015-01-20 00:20
Did you even give the players permissions to teleport to other plots? That is a different permission from plotme.use

**Comment by GotScrub** [comment] 2015-01-21 22:30
I believe I did? I don't see any other permissions listed on the spigot page other than plotme.use, plotme.admin, plotme.limit and plotme.block 

What would be the correct permission?

**Comment by MattBDev** [comment] 2015-01-21 23:35
look at our wiki page to see the permissions. this issue should not be active anymore and is getting annoying.

**Comment by GotScrub** [comment] 2015-01-21 23:44
I'm sorry it's getting annoying that I have issues that I don't know how to resolve... :\ You said the permission that allows people to tp to other plots is not plotme.use, I know it's not plotme.admin or plotme.block or plotme.limit. I've looked on your PlotMe | SpigotMC page and clicked Commands and Permissions and don't see anything that varies from the 4 mentioned above.

**Comment by MattBDev** [comment] 2015-01-22 00:03
It is in the plotme.admin section. One of the home commands.
