### ISSUE TITLE
PlotMe World Configs NOT Applying!

### ISSUE THREAD

**Issue by Galantiiss** [WorldCretornica/PlotMe-Core#348] opened 2015-07-23 19:14 UTC
Here is my DefaultGenerator World Config - 
    http://pastebin.com/sU2UqM6r
Here is my PlotMe Config - 
    http://pastebin.com/QM570xKW
My Server Version Is - 
    CraftBukkit 1.8.7
My PlotMe Version Is - 
    0.17.4
My PlotMe-DefaultGenerator Version Is -
    0.17.1
My Latest .log File
    http://pastebin.com/DJY7wE7E

The Issue -
When i create a PlotMe World with the DefaultGenerator it never spawns with the customization i make to it in the config. eg. Plot sizes , Different path blocks. If you need urther info just ask

Thank You !

**Comment by MattBDev** [comment] 2015-07-23 19:40
Not sure what the issue is so there is no description. I will be closing this. If you leave a description later on in this ticket I will reopen it and try to fix it.

**Comment by Galantiiss** [comment] 2015-07-23 19:50
I have added a desc to the ticket

**Comment by MattBDev** [comment] 2015-07-24 00:48
I'm unable to reproduce the issue. Try changing the name of your world to lowercase when you create it.

**Closed by MattBDev** 2015-07-24 00:48 UTC
