### ISSUE TITLE
Worldediting even when removed from plot

### ISSUE THREAD

**Issue by YepImRobbie** [WorldCretornica/PlotMe-Core#303] opened 2015-06-19 23:49 UTC
Hi, I use asyncworldedit and allow users to have world-edit.

If not added to plot = cannot build/world-edit
If added to plot = can build/world-edit
If removed from plot (prior to being added) = cannot build/can world-edit

It makes no sense, any fixes?

Version:
AsyncWorldEditInjector 2.1.3
Worldedit 6.0;3342-78f975b9
AsyncWorldEdit 2.1.5
AsyncWorldEdit-PlotMeCore014 2.1.5

Hi, I've probably got something certain un-updated and I'm being dumb, thanks.

**Comment by MattBDev** [comment] 2015-06-20 01:26
Duplicate, already fixed in 0.17 beta

**Closed** 2015-06-20 01:35 UTC
Labels: Duplicate

**Comment by MattBDev** [comment] 2015-06-20 01:37
Duplicate of #300 and #258
