### ISSUE TITLE
Small Request

### ISSUE THREAD

**Issue by DutchUser** [WorldCretornica/PlotMe-Core#281] opened 2015-05-19 11:57 UTC
Can multi-plotworld limit added
example: plotme.limit.plotworldx32.3 (plotworldx32 > world name)
example2: /plotme.limit.plotworldx64.1
and that can create only 3 in that plot world

And i got an small issue.
How can remove the claim command in the other world. 
This is not working:
  VIP:
    inheritance:
    - Speler
    permissions:
    - plotme.use
    - plotme.limit.15
    worlds:
      plotworldx64:
      - -plotme.use.claim

**Comment by MattBDev** [comment] 2015-05-19 12:56
Duplicate of #172

**Closed by MattBDev** 2015-05-19 12:56 UTC
