### ISSUE TITLE
Database error during UUID conversion

### ISSUE THREAD

**Issue by PrisonHeist** [WorldCretornica/PlotMe-Core#159] opened 2015-02-07 18:07 UTC
[18:05:00 INFO]: [PlotMe] Checking if conversion to UUID needed...
[18:05:00 WARN]: [PlotMe] Invalid name found : (player), removing.
[18:05:01 WARN]: [PlotMe] Invalid name found : @, removing.
[18:05:01 WARN]: [PlotMe] Invalid name found : @a, removing.
[18:05:01 WARN]: [PlotMe] Invalid name found : @all, removing.
[18:05:01 WARN]: [PlotMe] Invalid name found : [h]mmooney, removing.
[18:05:01 WARN]: [PlotMe] Invalid name found : \8, removing.
[18:05:01 WARN]: [PlotMe] Invalid name found : ^, removing.
[18:05:01 WARN]: [PlotMe] Invalid name found : _), removing.
[18:05:01 WARN]: [PlotMe] Invalid name found : _theepicbanana?, removing.
[18:05:01 INFO]: [PlotMe] Fetching 91 UUIDs from Mojang servers...
[18:05:03 ERROR]: [PlotMe] Conversion to UUID failed :
[18:05:03 ERROR]: [PlotMe] [SQLITE_ERROR] SQL error or missing database (no such
 table: TEMPPLOTMEALLOWED)
[18:05:03 ERROR]: [PlotMe]   org.sqlite.DB.newSQLException(DB.java:383)
[18:05:03 ERROR]: [PlotMe]   org.sqlite.DB.newSQLException(DB.java:387)
[18:05:03 ERROR]: [PlotMe]   org.sqlite.DB.throwex(DB.java:374)
[18:05:03 ERROR]: [PlotMe]   org.sqlite.NativeDB.prepare(Native Method)
[18:05:03 ERROR]: [PlotMe]   org.sqlite.DB.prepare(DB.java:123)
[18:05:03 ERROR]: [PlotMe]   org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
[18:05:03 ERROR]: [PlotMe]   org.sqlite.Conn.prepareStatement(Conn.java:404)
[18:05:03 ERROR]: [PlotMe]   org.sqlite.Conn.prepareStatement(Conn.java:399)
[18:05:03 ERROR]: [PlotMe]   org.sqlite.Conn.prepareStatement(Conn.java:383)
[18:05:03 ERROR]: [PlotMe]   com.worldcretornica.plotme_core.SqlManager$2.run(Sq
lManager.java:1851)
[18:05:03 ERROR]: [PlotMe]   org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.
run(CraftTask.java:71)
[18:05:03 ERROR]: [PlotMe]   org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsync
Task.run(CraftAsyncTask.java:53)
[18:05:03 ERROR]: [PlotMe]   java.util.concurrent.ThreadPoolExecutor.runWorker(U
nknown Source)
[18:05:03 ERROR]: [PlotMe]   java.util.concurrent.ThreadPoolExecutor$Worker.run(
Unknown Source)
[18:05:03 ERROR]: [PlotMe]   java.lang.Thread.run(Unknown Source)

**Comment by MattBDev** [comment] 2015-02-07 18:07
Duplicate of #156

**Closed by MattBDev** 2015-02-07 18:07 UTC
Labels: Duplicate
