### ISSUE TITLE
Conversion to UUID failed

### ISSUE THREAD

**Issue by TheChampTF** [WorldCretornica/PlotMe-Core#158] opened 2015-02-07 11:50 UTC
Environment:
Java version: 1.8.0_31 Oracle Corporation
Operating system: Linux 2.6.38-8-server amd64
Bukkit version: git-Bukkit-e81edfc (MC: 1.8)

Plugin: PlotMe 0.16.1

[12:44:53 ERROR]: [PlotMe] Conversion to UUID failed :
[12:44:53 ERROR]: [PlotMe] [SQLITE_ERROR] SQL error or missing database (no such table: TEMPPLOTMEALLOWED)
[12:44:53 ERROR]: [PlotMe]   org.sqlite.DB.newSQLException(DB.java:383)
[12:44:53 ERROR]: [PlotMe]   org.sqlite.DB.newSQLException(DB.java:387)
[12:44:53 ERROR]: [PlotMe]   org.sqlite.DB.throwex(DB.java:374)
[12:44:53 ERROR]: [PlotMe]   org.sqlite.NativeDB.prepare(Native Method)
[12:44:53 ERROR]: [PlotMe]   org.sqlite.DB.prepare(DB.java:123)
[12:44:53 ERROR]: [PlotMe]   org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
[12:44:53 ERROR]: [PlotMe]   org.sqlite.Conn.prepareStatement(Conn.java:404)
[12:44:53 ERROR]: [PlotMe]   org.sqlite.Conn.prepareStatement(Conn.java:399)
[12:44:53 ERROR]: [PlotMe]   org.sqlite.Conn.prepareStatement(Conn.java:383)
[12:44:53 ERROR]: [PlotMe]   com.worldcretornica.plotme_core.SqlManager$2.run(SqlManager.java:1851)
[12:44:53 ERROR]: [PlotMe]   org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53)
[12:44:53 ERROR]: [PlotMe]   org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[12:44:53 ERROR]: [PlotMe]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:44:53 ERROR]: [PlotMe]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[12:44:53 ERROR]: [PlotMe]   java.lang.Thread.run(Thread.java:745)

**Comment by MattBDev** [comment] 2015-02-07 14:59
Duplicate of #156
Please refer to that issue for future updates regarding a fix.

**Closed by MattBDev** 2015-02-07 14:59 UTC

**Comment by TheChampTF** [comment] 2015-02-07 15:06
Well the issue is from 1.6 to 1.6.1 not the outdated version

**Comment by MattBDev** [comment] 2015-02-07 15:09
I am well aware. This is the same issue as #156 so I am not keeping two tickets open for the same exact issue.
